#!/bin/bash
player=mpv

PS3="Select a station: ";
select s in 1 2 3 4 5 6 7 1x "Asian Network an" "Nations & Local lcl";do
    break;
done;
s=($s);
$player --cache-min=40 -playlist "http://www.bbc.co.uk/radio/listen/live/r"${s[@]: -1}".asx";
