#!/bin/sh
# Usage: colordump
# Dump 256 ansi colors to the terminal.

printf "ANSI Colours:\n-------------\n\n"

i=0
row=0
while [ $i -lt 255 ]; do
    newrow=$((i / 10))
    [ $newrow -ne $row ] && printf "\n"
    row=$newrow
    printf "\e[%dm %03d \e[0m" $i $i
    i=$((i + 1))
done

printf '\n\n     e.g., "\\e[41mTEXT\\e[0m" '
printf "\e[41m(for TEXT like this)\e[0m\n"

printf "\n256 Colours:\n------------\n\n"

i=0
row=0
while [ $i -lt 255 ]; do
    newrow=$((i / 10))
    [ $newrow -ne $row ] && printf "\n"
    row=$newrow
	printf "\e[38;5;%dm %03d \e[0m" $i $i
	printf "\e[48;5;%dm %03d \e[0m" $i $i
	i=$((i + 1))
done

printf '\n\n    e.g., "\\e[38;5;24mTEXT\\[e0m" '
printf "\e[38;5;24m(for TEXT like this)\e[0m\n"

printf '    e.g., "\\e[48;5;24mTEXT\\[e0m" '
printf "\e[48;5;24m(for TEXT like this)\e[0m\n"

awk 'BEGIN{
	s="/\\/\\/\\/\\/\\"; s=s s s s s s s s;
	for (colnum = 0; colnum<77; colnum++) {
		r = 255-(colnum*255/76);
		g = (colnum*510/76);
		b = (colnum*255/76);
		if (g>255) g = 510-g;
		printf "\033[48;2;%d;%d;%dm", r,g,b;
		printf "\033[38;2;%d;%d;%dm", 255-r,255-g,255-b;
		printf "%s\033[0m", substr(s,colnum+1,1);
	}
	printf "\n";
}'