#!/bin/bash
# Created:  Wed 23 Apr 2014 12:58 pm
# Author:   Josh Wainwright
# Filename: commitAll

set -o nounset
#set -o errexit

verbose=true
justList=false
pullAll=false
pushAll=false
commit=false
list=""
ignore=("Osaka" "plugged" "TLPs")
include=("JoshWainwright|josh")
customcmd=""

verbose() {
	set +u
	if $verbose; then
		echo -e ${2} "$1"
	fi
	set -u
}

getGitRepos() {
	if hash locate 2>/dev/null; then
		list=$(dirname $(locate -br '\.git$'))
	else
		verbose "Command locate not availible. Using find instead."
		list=$(find ~/ -name ".git" -exec dirname {} \; 2> /dev/null)
	fi

	for i in "${ignore[@]}"; do
		list=$(sed "/${i}/d" <<< "$list")
	done

	if [[ ${#include[@]} -ne 0 ]]; then
		local includeString=""
		for i in "${include[@]}"; do
			includeString+="$i""|"
		done
		includeString=${includeString%?}
		list=$(egrep "$includeString" <<< "$list")
	fi

}

pullAll() {
	if $pullAll; then
		git -c color.pull=always pull origin master 2>&1 | sed 's/^/\t/'
	fi
}

pushAll() {
	if $pushAll; then
		if [[ $1 -gt 0 ]]; then
			git push --color=always 2>&1 | sed 's/^/\t/'
		fi
	fi
}

currentDir=$(pwd)
cd ~/

while getopts "Vlducx:i:r:" opt; do
	case "$opt" in
		V)
			verbose=false
			;;
		l)
			justList=true
			;;
		d)
			pullAll=true
			;;
		u)
			pushAll=true
			;;
		c)
			commit=true
			;;
		x)
			ignore+=("$OPTARG")
			;;
		i)
			include+=("$OPTARG")
			;;
		r)
			customcmd=("$OPTARG")
			;;
		*)
			echo "Flag "$opt" not recognised."
			exit 0
			;;
	esac
done
shift $((OPTIND-1))

#### Start script ####

getGitRepos

if $justList; then
	echo "$list"
	exit
fi

# while read -r gitDir; do
for gitDir in $(echo $list); do

	addNewline=false
	cd $gitDir;

	verbose "$gitDir"
	if ! git diff --quiet --ignore-submodules HEAD &>/dev/null; then

		numberLines=$(git status -s | wc -l);

		if [[ "$numberLines" != "0" ]]; then
			verbose  "\tChanged $numberLines"
			git -c color.status=always status --ignore-submodules --short | sed 's/^/\t/'
			addNewline=true
		fi

		if $commit; then
			git gui
		fi

	fi
	if [[ "x$customcmd" != "x" ]]; then
		eval "$customcmd" | sed 's/^/\t\t/'
	fi

	numberAhead=$(git log --branches --not --remotes --oneline 2> /dev/null | wc -l)
	if [[ "$numberAhead" -ne 0 ]]; then
		verbose "\tAhead: $numberAhead"
		git log --color=always --branches --not --remotes --oneline --decorate | sed 's/^/\t/'
		addNewline=true
	fi

	pullAll
	pushAll $numberAhead

	if $addNewline; then
		verbose
	fi

done <<< "$list"

cd $currentDir
