#!/bin/bash
# Created:  Tue 01 Sep 2015
# Modified: Tue 01 Sep 2015
# Author:   Josh Wainwright
# Filename: define

dictfile=~/.dictionary.txt

if [ -e ${dictfile} ]; then
	w=$1
	while [ ${#w} -gt 3 ]; do
		grep -i "^${w}" ${dictfile}
		if [ $? -eq 0 ]; then
			break
		fi
		w=${w%?}
	done
else
	echo "${dictfile} does not exist."
fi
