#!/bin/bash

dir=/home/josh/Pictures/Wallpapers

cd $dir
  # | egrep "500px|imgur|flickr|squarespace" \

url=$(curl -s 'http://www.reddit.com/r/earthporn' \
  | tr '"' '\n' \
  | egrep '^http://.*\.(jpg)|(png)' \
  | egrep -v 'reddit' \
  | shuf -n1 \
  | sed 's/\?.*$//g' \
  | uniq)

ext="${url##*.}"
sha=$(cksum <<< "$url" | tr -d ' ')
wget -nc "$url" -O "$sha.$ext"

feh --bg-fill $sha.$ext

cd -
