#!/bin/bash
# Created:  Mon 26 May 2014
# Modified: Mon 09 Mar 2015
# Author:   Josh Wainwright
# Filename: fed (Folder Encrypt Decrypt)
set -o nounset

function echoerr() {
	>&2 echo $@
}

exists() {
	command -v "$@" > /dev/null
}
[[ $# -eq 0 ]] && echoerr "Please provide a file to encrypt or decrypt" && exit 1

remove=true
if [[ $1 == "-n" ]]; then
	remove=false
	shift
fi

arg="$1"
tare="tar.gz"

exists gpg || exit 1
exists tar || exit 1

if [[ -d $arg ]]; then
	echo "Compressing"
	trap "echo [Cleaning]; rm $arg.$tare" SIGINT
	tar czf $arg.$tare $arg

	echo "Encrypting"
	trap "echo [Cleaning]; rm $arg.$tare*" SIGINT
	gpg -e -r "Josh Wainwright" $arg.$tare
	gpg_good=$?

	rm $arg.$tare
	if $remove; then
		echo "Cleaning"
		[ $gpg_good -eq 0 ] && [ -f $arg.$tare ] && rm -r $arg
	fi

elif [[ "$arg" == *.gpg ]]; then
	fname=${arg%.*}
	echo "Decrypting"
	gpg -o $fname -d $arg

	echo "Decompressing"
	tar xzf $fname

	echo "Cleaning"
	rm $fname
elif [[ -f $arg ]]; then
	>&2 echoerr "For files, please use standard gpg"
else
	>&2 echoerr "Folder does not exist"
fi

exit 0
