#!/bin/bash
# folder encrypt/decrypt
set -o nounset
set -o errexit

remove=true
if [[ $1 == "-n" ]]; then
	remove=false
	shift
fi

arg="$1"
tare="tar.gz"

hash gpg || exit 1
hash tar || exit 1

if [[ -d $arg ]]; then
	echo "Compressing"
	trap "echo [Cleaning]; rm $arg.$tare" SIGINT
	tar czf $arg.$tare $arg

	echo "Encrypting"
	trap "echo [Cleaning]; rm $arg.$tare*" SIGINT
	gpg -e -r "Josh Wainwright" $arg.$tare

	if $remove; then
		echo "Cleaning"
		[ $? -eq 0 ] && [ -f $arg.$tare ] && rm -r $arg $arg.$tare
	fi

elif [[ "$arg" == *.gpg ]]; then
	fname=${arg%.*}
	echo "Decrypting"
	gpg -o $fname -d $arg

	echo "Decompressing"
	tar xzf $fname

	echo "Cleaning"
	rm $fname
else
	>&2 echo "File or folder does not exist"
fi
