#!/bin/bash
# Created:  2016-04-18
# Modified: Wed 07 Dec 2016
# Author:   Josh Wainwright
# Filename: git-log.sh

printf ':GitLP\n' | vis && stty sane

exit 0

function input() {
	case $1 in
		$'\e') exit 1 ;;
		q) exit 1 ;;
		J) increment 10 ;;
		j) increment 1 ;;
		K) increment -10 ;;
		k) increment -1 ;;
		g) x=1 ;;
		*) increment 1 ;;
	esac
}

function increment() {
	local tmp=$((x + $1))
	if [ $tmp -lt 0 ]; then
		x=0
	else
		x=$tmp
	fi
}

x=${1:-0}
increment 0

while true; do
	#git log -a -p -n 1 HEAD~$x
	c=$(git show --pretty=format:%H --no-patch HEAD~$x)
	show=$(git show --no-patch --color $c)
	diff=$(git --no-pager diff --color $c^ $c)
	clear
	printf "%s\n\n%s\n" "$show" "$diff" | less -R -F -X -S
	read -N 1 -s char
	input $char
done
