#! /bin/bash

total=0

printf "\t%-8s\t%-8s\t%-8s\n" "Before" "After" "Diff"
for folder in *; do
	cd "$folder" > /dev/null
	echo "$folder"
	before=$(du -sb . | awk '{print $1}')
	hbefore=$(numfmt --to=iec <<< $before)
	# printf "\t%-10s : %-15s%s\n" "Before" $before $hbefore

	git gc --aggressive --prune=all > /dev/null &>2

	after=$(du -sb . | awk '{print $1}')
	hafter=$(numfmt --to=iec <<< $after)
	# printf "\t%-10s : %-15s%s\n" "After" $after $hafter
	diff=$(( $before - $after ))
	hdiff=$(numfmt --to=iec <<< $diff)
	# printf "\t%-10s : %-15s%s\n" "Difference" $diff $hdiff
	printf "\t%-8s\t%-8s\t%-8s\n" $hbefore $hafter $hdiff
	total=$((total + $diff))
	cd .. > /dev/null
done
echo "Total savings: $total ($(numfmt --to=iec <<< $total))"
