#!/bin/bash
# Created:  Wed 04 Feb 2015
# Modified: Mon 16 Feb 2015
# Author:   Josh Wainwright
# Filename: lsall
set -o nounset
set -o errexit
function echoerr() {
	>&2 echo $@
}

function usage() {
helptext="$(basename $0) [-dfvh] [-m depth]

lsall = List All. List all files or directories under the current location,
ignoring common version control specific files.

	-h       Show this help text.
	-v       Print the find command which would be used.
	-d       List directories instead of files.
	-f       Print files with \$HOME replaced with ~.
	-m depth Search only to a directory depth of depth.
	-n       Don't output a count of number of files.
"
printf "$helptext"
}

ftype="-type f"
filesfile=false
verbose=false
maxdepth=""
cntout=true
while getopts "dfvhm:n" opt; do
	case "$opt" in
		d) ftype="-type d" ;;
		f) filesfile=true ;;
		v) verbose=true ;;
		h) usage && exit 0 ;;
		m) maxdepth="-maxdepth $OPTARG" ;;
		n) cntout=false ;;
		*) echoerr "Flag "$opt" not recognised."
			exit 1
			;;
	esac
done
shift $((OPTIND-1))

path="${@:-.}"
eval $filesfile && path=$(pwd)

cmd="find "$path" "$maxdepth" \
         \( \
            -name .svn -o -name .git -o -name .hg -o -name .bzr \
         \) \
       -prune -o \
         \( \
            -path \"*/vim/tmp\" -o \
            -path \"*/.config/cygwin\" \
         \) \
       -prune -o \
         \( \
            -name .\#\*   -o -name \*.o     -o -name \*\~   -o -name \*.bin -o \
            -name \*.lbin -o -name \*.so    -o -name \*.a   -o -name \*.ln  -o \
            -name \*.blg  -o -name \*.bbl   -o -name \*.elc -o -name \*.lof -o \
            -name \*.glo  -o -name \*.idx   -o -name \*.lot -o -name \*.fmt -o \
            -name \*.tfm  -o -name \*.class -o -name \*.fas -o -name \*.lib -o \
            -name \*.fasl -o -name \*.ufsl  -o -name \*.fsl -o -name \*.dxl -o \
            -name \*.la   -o -name \*.gmo   -o -name \*.mo  -o -name \*.toc -o \
            -name \*.aux  -o -name \*.cp    -o -name \*.fn  -o -name \*.ky  -o \
            -name \*.pg   -o -name \*.tp    -o -name \*.vr  -o -name \*.cps -o \
            -name \*.fns  -o -name \*.kys   -o -name \*.pgs -o -name \*.tps -o \
            -name \*.vrs  -o -name \*.pyc   -o -name \*.pyo \
          \) \
       -prune -o \
       \( $ftype -print \)"

if $filesfile; then
	cmd="$cmd | sed \"s#^$HOME/#~/#\""
fi
if $verbose; then
	echo $cmd
elif "$cntout"; then
	eval "$cmd" | tee >(wc -l >&2)
else
	eval "$cmd"
fi
