#!/bin/bash
# Created:  Mon 19 Jan 2015
# Modified: Wed 21 Jan 2015
# Author:   Josh Wainwright
# Filename: massrename
set -o nounset
set -o errexit

function escape_spaces() {
	#sed -i 's/ /\\ /g' $1
	sed -i -e 's/^/"/' -e 's/$/"/g' $1
}

list=$(mktemp)
orig=$(mktemp)
ren=$(mktemp)

#if [ $# -eq 0 ]; then
if read -t 0; then
	cat > $list
else
	find . -maxdepth 1 -type f > $list
fi

echo "### Files to edit ###"
cat $list
echo "#####################"

if [[ ! -s $list ]]; then
	echo "No files to rename"
	exit 1
fi

cp $list $orig

hash procps && ps='procps'

TTY="/dev/"$($ps -o tty=, -o pid= | grep $$ | cut -d " " -f 1)
vim $list < $TTY > $TTY

lines_before=$(wc -l < $orig)
lines_after=$(wc -l < $list)
if [[ $lines_before -ne $lines_after ]]; then
	echo "Don't delete or add lines!"
	exit 1
fi

escape_spaces $orig
escape_spaces $list
sed -i 's/$/@#sep#@/' $orig
paste -d '' $orig $list > $ren

awk -F "@#sep#@" '$1 != $2 {printf "mv -v %s %s\n", $1, $2}' $ren | bash

rm $ren $list $orig
