#!/usr/bin/env python
# Created:  Thu 16 Apr 2015
# Modified: Wed 08 Jul 2015
# Author:   Josh Wainwright
# Filename: massrename.py

import sys, os, tempfile
from subprocess import call

if len(sys.argv) > 1:
    if sys.argv[1] == '-r':
        listin = [os.path.join(dp, f) for dp, dn, fn in os.walk('.') for f in fn]
    else:
        listin = sys.argv[1:]
else:
    listin = [f for f in os.listdir('.') if os.path.isfile(f)]

if len(listin) == 0:
    print("No files to rename")
    sys.exit(1)

print("### Files to edit ###")
print('\n'.join(listin))
print("#####################")

EDITOR = os.environ.get('EDITOR', 'vim')
with tempfile.NamedTemporaryFile() as tmpfile:
    tmpfile.write('\n'.join(listin))
    tmpfile.seek(0)

    call([EDITOR, tmpfile.name])

    listout = tmpfile.readlines()
    listout = [f.rstrip() for f in listout]

if len(listin) != len(listout):
    print("Don't add or delete lines")
    sys.exit(1)

for i, o in zip(listin, listout):
    if not i == o:
        print(i + " -> " + o)
        os.rename(i, o)
