#!/usr/bin/env python
# Created:  Thu 16 Apr 2015
# Modified: Thu 28 May 2015
# Author:   Josh Wainwright
# Filename: massrename.py

import sys
import os
import os.path
import tempfile

if len(sys.argv) > 1:
    listin = sys.argv[1:]
elif not sys.stdin.isatty():
    listin = sys.stdin.readlines()
    listin = [f.rstrip() for f in listin]
else:
    listin = [f for f in os.listdir('.') if os.path.isfile(f)]

if len(listin) == 0:
    print("No files to rename")
    sys.exit(1)

print("### Files to edit ###")
for f in listin:
    print(f)
print("#####################")

tmpfile = tempfile.NamedTemporaryFile()
for f in listin:
    tmpfile.write(f + '\n')
tmpfile.seek(0)

os.system('vim ' + tmpfile.name)

listout = tmpfile.readlines()
listout = [f.rstrip() for f in listout]

if not len(listin) == len(listout):
    print("Don't add or delete lines")
    sys.exit(1)

for i, o in zip(listin, listout):
    if not i == o:
        print(i + " -> " + o)
        os.rename(i, o)
