#!/bin/bash
# Created:  Tue 24 Mar 2015
# Modified: Fri 08 Apr 2016
# Author:   Josh Wainwright
# Filename: ntime

set -o nounset

if [ $# -gt 1 ]; then
	num="$1"
	shift
	cmd="$@"
else
	echo "Wrong number of args" >&2
	exit 1
fi

start_t=$(date +%s%3N)

for i in $(seq 1 $num); do
	eval "$cmd"
done

end_t=$(date +%s%3N)

av_t=$(echo "scale=5; ($end_t - $start_t)/$num" | bc -l )
>&2 printf "Av time: %s ms\n" "$av_t"
