#!/bin/bash

#Quality setting 2 = 240p
#                3 = 360p
#                4 = 480p
#                7 = 720p
#                1 = 1080p

qual=4
dir="/home/josh/Videos/Youtube"

options="--download-dir=$dir -$qual -d"

if [ $# -eq 0 ]; then
    youtube-viewer -S joshwainwright1 $options
else
    youtube-viewer "$@" $options
fi

if [ "$(ls -A $dir)" ]; then
    for file in $dir/*; do
        open "$file"
    done

	read -p "Delete all downloaded Youtube videos? [yn] " -n 1 -r
	echo    # (optional) move to a new line
	if [[ $REPLY =~ ^[Yy]$ ]]; then
        rm -v $dir/*
	fi

fi
