all: up down set

up: brightness.c
	gcc -g -Wall -o brightness-up -D BRIGHTNESS_UP brightness.c

down: brightness.c
	gcc -g -Wall -o brightness-down -D BRIGHTNESS_DOWN brightness.c

set: brightness.c
	gcc -g -Wall -o brightness-set -D BRIGHTNESS_SET brightness.c
